### PR TITLE
Allow decoding with multi-char keys

### PR DESCRIPTION
**Pull request by yourcodesucks**
To base-128 and beyond!

### CODE REVIEW

**Comment by DonutEspresso** [comment]
Thanks for the PR! 🎉  Would you mind adding a sample test, or provide some sample strings that we could build a test with?

**Comment by yourcodesucks** [comment]
Sure, give me a couple of days

**Comment by DonutEspresso** [comment]
Great, thank you!

**Comment by yourcodesucks** [comment]
Hi Alex, it took more than a couple of days, but I just checked in some tests.

**Comment by anonymoussprocket** [comment]
Hey Alex, do you think you think the PR will get merged and the build updated on npm?

**Comment by DonutEspresso** [comment]
@yourcodesucks omg, I'm so sorry, I totally dropped the ball on this. I don't know if you still need this, but I've added the core of your functionality in #7 .

**Comment by yourcodesucks** [comment]
it's no problem. some version of npm broke my ability to include packages via git and instead of figuring it out I [reimplemented it elsewhere](https://github.com/Cryptonomic/ConseilJS/blob/08bbd9db7246c3e7a6b097f3b1b3428238f45c73/src/chain/tezos/TezosMessageUtil.ts#L489).

**Pull request closed without merging**
